# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OpenGL-Shader
version:      1.00
version_from: Shader.pm
installdirs:  site
requires:
    OpenGL:                        0.56

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
